<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <DocumentationFile>doc-api-sdk-example.xml</DocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ByteSize" Version="2.1.1" />
    <PackageReference Include="Castle.Core" Version="5.1.1" />
    <PackageReference Include="Castle.Windsor" Version="6.0.0" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="Asp.Versioning.Mvc" Version="8.1.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.1.0" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.4.0" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.4.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.4.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.9.0" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.9.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Net.Web.Api.Sdk\Net.Web.Api.Sdk.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="App_Data\Certficates\net-web-api-jwt-signing.pfx" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="App_Data\Certficates\net-web-api-jwt-validating.cer" CopyToOutputDirectory="PreserveNewest" />
    <Content Update="token-example.config" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="SwaggerConfiguration.json" />
  </ItemGroup>
</Project>
