<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <DocumentationFile>Documentation\Swagger\Resources\doc-api-sdk.xml</DocumentationFile>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="ByteSize" Version="2.1.2" />
    <PackageReference Include="Castle.Core" Version="5.1.1" />
    <PackageReference Include="Castle.Windsor" Version="6.0.0" />
    <PackageReference Include="LiteDB" Version="5.0.21" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="8.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning.ApiExplorer" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.Cors" Version="2.2.0" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.2.1" />
    <PackageReference Include="Microsoft.IdentityModel.Logging" Version="8.2.1" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.2.1" />
    <PackageReference Include="Microsoft.Web.Xdt" Version="3.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NuGet.Protocol" Version="6.12.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.2.1" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters" Version="1.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.SystemWebAdapters.CoreServices" Version="1.4.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="9.0.6" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Client" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.3.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.WebHost" Version="5.3.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Cors" Version="5.3.0" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Versioning" Version="4.2.2" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Versioning.ApiExplorer" Version="4.2.2" />
    <PackageReference Include="Swashbuckle.Core" Version="5.6.0" />
    <PackageReference Include="MultipartDataMediaFormatter.V2" Version="2.1.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Documentation\Swagger\Resources\SwaggerConfigurationSdk.json" />
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Include="Security\Resources\token-sdk.config" />
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Documentation\Swagger\Resources\index.html" />
    <EmbeddedResource Include="Documentation\Swagger\Resources\logo-16x16.png" />
    <EmbeddedResource Include="Documentation\Swagger\Resources\logo-32x32.png" />
    <EmbeddedResource Include="Documentation\Swagger\Resources\swagger-ui-override.css" />
    <EmbeddedResource Include="Documentation\Swagger\Resources\swagger-ui-override.js" />
    <EmbeddedResource Include="Documentation\Swagger\Resources\swagger.html" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Documentation\Swagger\Resources\doc-api-sdk.xml" />
  </ItemGroup>
</Project>